# GenerateBuildInfo.cmake
# Usage: cmake -DSOURCE_DIR=<path> -DOUTPUT_FILE=<path> -P GenerateBuildInfo.cmake

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR must be defined")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE must be defined")
endif()

# 1. UTC Timestamp
string(TIMESTAMP BUILD_TIME_UTC "%Y-%m-%dT%H:%M:%SZ" UTC)

# 2. Git Commit / Describe
execute_process(
    COMMAND git describe --always --dirty --tags
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT GIT_COMMIT_HASH)
    execute_process(
        COMMAND git rev-parse --short HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_COMMIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
endif()
if(NOT GIT_COMMIT_HASH)
    set(GIT_COMMIT_HASH "unknown")
endif()

# 3. Deterministic SHA-256 of major source inputs
file(GLOB_RECURSE ALL_C "${SOURCE_DIR}/*.c")
file(GLOB_RECURSE ALL_H "${SOURCE_DIR}/*.h")
file(GLOB_RECURSE ALL_PIO "${SOURCE_DIR}/*.pio")
file(GLOB_RECURSE ALL_CMAKE "${SOURCE_DIR}/*CMakeLists.txt" "${SOURCE_DIR}/*.cmake")

set(ALL_RAW_SOURCES ${ALL_C} ${ALL_H} ${ALL_PIO} ${ALL_CMAKE})
set(FILTERED_SOURCES "")
foreach(F ${ALL_RAW_SOURCES})
    if(NOT F MATCHES "/(build|build[^/]*)/" AND NOT F MATCHES "/generated/" AND NOT F MATCHES "/\\.")
        list(APPEND FILTERED_SOURCES "${F}")
    endif()
endforeach()

list(REMOVE_DUPLICATES FILTERED_SOURCES)
list(SORT FILTERED_SOURCES)

set(MANIFEST_STR "")
foreach(SRC_PATH ${FILTERED_SOURCES})
    file(RELATIVE_PATH REL_PATH "${SOURCE_DIR}" "${SRC_PATH}")
    file(SHA256 "${SRC_PATH}" FILE_SHA)
    string(APPEND MANIFEST_STR "${REL_PATH}:${FILE_SHA}\n")
endforeach()

string(SHA256 SOURCE_MANIFEST_SHA256 "${MANIFEST_STR}")

# Ensure output directory exists
get_filename_component(OUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUT_DIR}")

# Prepare generated header content
set(CONTENT "/* Auto-generated by GenerateBuildInfo.cmake. Do not edit. */\n")
string(APPEND CONTENT "#ifndef BUILD_INFO_GEN_H\n")
string(APPEND CONTENT "#define BUILD_INFO_GEN_H\n\n")
string(APPEND CONTENT "#define BUILD_INFO_TIME_UTC      \"${BUILD_TIME_UTC}\"\n")
string(APPEND CONTENT "#define BUILD_INFO_GIT_COMMIT    \"${GIT_COMMIT_HASH}\"\n")
string(APPEND CONTENT "#define BUILD_INFO_SOURCE_SHA256 \"${SOURCE_MANIFEST_SHA256}\"\n\n")
string(APPEND CONTENT "#endif /* BUILD_INFO_GEN_H */\n")

if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" EXISTING_CONTENT)
    string(REGEX MATCH "#define BUILD_INFO_SOURCE_SHA256 \"([^\"]+)\"" _M1 "${EXISTING_CONTENT}")
    set(OLD_SHA "${CMAKE_MATCH_1}")
    string(REGEX MATCH "#define BUILD_INFO_GIT_COMMIT    \"([^\"]+)\"" _M2 "${EXISTING_CONTENT}")
    set(OLD_GIT "${CMAKE_MATCH_1}")
    if(OLD_SHA STREQUAL SOURCE_MANIFEST_SHA256 AND OLD_GIT STREQUAL GIT_COMMIT_HASH)
        # Identical source tree and commit
        return()
    endif()
endif()

file(WRITE "${OUTPUT_FILE}" "${CONTENT}")
message(STATUS "[BuildInfo] Generated ${OUTPUT_FILE}: UTC=${BUILD_TIME_UTC}, Git=${GIT_COMMIT_HASH}, SHA256=${SOURCE_MANIFEST_SHA256}")
